name: deploy-website

on:
  push:
    branches:
      - main
    paths:
      - website/**

jobs:
  deploy-production:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6
      - run: pnpm install
      - run: pnpm build:website
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy files to S3
        run: |
          aws s3 sync ./website/dist s3://sanersocialmedia-website-production
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2V7OUP9M6ZDBN \
            --paths "/*"
